### ISSUE TITLE
Streetcred wallet shows "Attributes are not available at the moment"?

### ISSUE THREAD

**Issue by matthieulux** [streetcred-id/issuer-reference-app#10] opened 2020-05-05 11:59 UTC
After deploying locally iiw demo and configuring as per instructions, the connection request using the QR code is successful and I am able to establish a new connection and receive a credential, however it is empty and the message "Attributes are not available at the moment" appears under it.

Could this be due to recent updates in the API? in the Streetcred app? Thanks,

**Comment by euroledger** [comment] 2020-05-10 11:41
I had the same issue. I changed the server.js code to put the parameters of the credential in the createCredential() call and modified the issueCredential() call to only have the credential_id. This worked. Possibly due to API updates as you say

**Comment by bartcant** [comment] 2020-05-22 22:31
@euroledger  
Can you share the updated server.js code that works ?

**Comment by bartcant** [comment] 2020-05-23 00:32
I am experiencing the same issue with  "Attributes are not available"

**Comment by drakebw** [comment] 2020-06-02 16:38
@bartcant I was able to reproduce this issue and was able to fix it. I am working on a PR now to update the demo, but I will share my working code with you in the interest of getting you a response sooner.

The key is that, as @euroledger explained, an API update moved the location where the credential values are passed. Instead of being in the client.issueCredential() call (like in the current demo), it should be done in the client.createCredential() call. You can see how I did it below.

`
app.post('/webhook', async function (req, res) {
    try {
        console.log("got webhook" + req + "   type: " + req.body.message_type);
        if (req.body.message_type === 'new_connection') {
            console.log("new connection notif");

            const attribs = cache.get(req.body.object_id)
            if (attribs) {
                let param_obj = JSON.parse(attribs);
                let params = {
                    credentialOfferParameters: {
                        definitionId: process.env.CRED_DEF_ID,
                        connectionId: req.body.object_id,
                        credentialValues: {
                            "Full Name": param_obj["name"],
                            "Title": param_obj["title"],
                            "Company Name": param_obj["org"],
                            "Phone Number": param_obj["phone"],
                            "Email": param_obj["email"]
                        }
                    }
                }
                await client.createCredential(params);
            }
        }
        else if (req.body.message_type === 'credential_request') {
            console.log("cred request notif");
            await client.issueCredential(req.body.object_id);
        }
    }
    catch (e) {
        console.log(e.message || e.toString());
    }
});
`

**Comment by drakebw** [comment] 2020-06-02 19:28
Fixed in [this PR](https://github.com/streetcred-id/iiw-demo/pull/12)

**Comment by bartcant** [comment] 2020-06-03 23:48
I retested with the latest code and the connection request is received after the scan, 
However the next steps (webhook) for sending the Credentials did not get kicked off in my case.

**Comment by drakebw** [comment] 2020-06-08 22:43
> I retested with the latest code and the connection request is received after the scan,
> However the next steps (webhook) for sending the Credentials did not get kicked off in my case.

You and I resolved this offline by updating the .env file to have correct credentials and IDs.

**Closed by drakebw** 2020-06-08 22:43 UTC
